/** *****************************************************************
			Even Fibonacci Numbers

  Q2. Each new term in the Fibonacci sequence is generated by adding 
      the previous two terms. By starting with 1 and 2, the first 10
      terms will be:
	  
		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
					
      By considering the terms in the Fibonacci sequence whose 
      values do not exceed four million, find the sum of the 
      even-valued terms.
	  
  A2. 4613732
***************************************************************** **/

#include <stdio.h>
#include <stdint.h>

int main(){
	uint64_t sum = 2;
	uint32_t n1 = 1;
	uint32_t n2 = 2;
	uint32_t n3 = n1 + n2;
	
	while(n3 < 4000000){
		n3 = n1 + n2;
		n1 = n2;
		n2 = n3;
		
		if (n3 % 2 == 0){
			sum += n3;
		}
	}
	
	printf("The sum of even valued terms of the Fibonacci sequence whose value does not exceed 4 million is %d.\n", sum);
		
	return 0;
}

